name: CI CD Static content
description: Static content for CI/CD

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 22.x

            - name: Install dependencies
              run: yarn install

            - name: Build
              run: yarn run build

        #  add deployment steps here
