name: PR Checks

on:
    pull_request:
        branches:
            - main

jobs:
    build-and-test:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [22.x]

        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Install and build
              run: yarn install && yarn run build
